backend:
  name: git-gateway
  branch: main
site_url: https://your-site.com
media_folder: static/images/uploads
public_folder: /images/uploads
publish_mode: editorial_workflow
collections:
  - name: 'blogposts'
    label: 'Blogposts'
    label_singular: 'Blogpost'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: 'blog/{{year}}-{{month}}-{{day}}-{{slug}}'
    format: yaml-frontmatter
    editor:
      preview: false
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Drafts
        field: draft
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Summary', name: 'summary', widget: 'string', required: false}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'talks'
    label: 'Talks'
    label_singular: 'Talk'
    folder: 'content/talk'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: 'talk/{{year}}-{{month}}-{{day}}-{{slug}}'
    format: yaml-frontmatter
    editor:
      preview: false
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Drafts
        field: draft
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Summary', name: 'summary', widget: 'string', required: false}
      - { label: 'Slides', name: 'slides', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }